// <auto-generated />
using System;
using CarRental.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CarRental.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260924074333_AddCompensationPolicies")]
    partial class AddCompensationPolicies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "car_status", new[] { "READY", "BOOKED", "RENTED", "INSPECTION", "MAINTENANCE", "REPAIR", "INACTIVE" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "car_transmission", new[] { "AUTO", "MANUAL" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "public", "fuel_type", new[] { "PETROL", "DIESEL", "ELECTRIC" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CarRental.API.Entities.CompensationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("calculation_type");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("compensation_policies");
                });

            modelBuilder.Entity("CarRental.API.Entities.PricingPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<decimal>("DiscountPercentage")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("discount_percentage");

                    b.Property<decimal>("HolidaySurcharge")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("holiday_surcharge");

                    b.Property<int>("MinDays")
                        .HasColumnType("integer")
                        .HasColumnName("min_days");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("pricing_policies");
                });

            modelBuilder.Entity("CarRental.API.Entities.RentalCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CarId")
                        .HasColumnType("uuid")
                        .HasColumnName("car_id");

                    b.Property<int?>("MinAge")
                        .HasColumnType("integer")
                        .HasColumnName("min_age");

                    b.Property<string>("OtherConditions")
                        .HasColumnType("text")
                        .HasColumnName("other_conditions");

                    b.Property<int?>("RequireDrivingYears")
                        .HasColumnType("integer")
                        .HasColumnName("require_driving_years");

                    b.HasKey("Id");

                    b.HasIndex("CarId")
                        .IsUnique();

                    b.ToTable("rental_conditions");
                });

            modelBuilder.Entity("CarRental.API.Entities.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentMileage")
                        .HasColumnType("integer")
                        .HasColumnName("current_mileage");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("base_price");

                    b.Property<decimal>("DepositAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("deposit_amount");

                    b.Property<decimal?>("ExtraKmRate")
                        .HasColumnType("numeric")
                        .HasColumnName("extra_km_rate");

                    b.Property<string>("FuelReturnPolicy")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("fuel_return_policy");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasColumnType("public.fuel_type")
                        .HasColumnName("fuel_type");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("license_plate");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("brand");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("integer")
                        .HasColumnName("manufacture_year");

                    b.Property<int?>("MileageLimit")
                        .HasColumnType("integer")
                        .HasColumnName("included_km_per_day");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("model");

                    b.Property<DateTime?>("NextMaintenanceDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_maintenance_date");

                    b.Property<int?>("NextMaintenanceMileage")
                        .HasColumnType("integer")
                        .HasColumnName("next_maintenance_mileage");

                    b.Property<string>("PickupLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("pickup_location");

                    b.Property<int>("Seats")
                        .HasColumnType("integer")
                        .HasColumnName("seats");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("public.car_status")
                        .HasColumnName("status");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("public.car_transmission")
                        .HasColumnName("transmission");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LicensePlate")
                        .IsUnique();

                    b.ToTable("cars");
                });

            modelBuilder.Entity("CarRental.API.Entities.PricingPolicy", b =>
                {
                    b.HasOne("CarRental.API.Entities.Vehicle", "Vehicle")
                        .WithMany("PricingPolicies")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarRental.API.Entities.RentalCondition", b =>
                {
                    b.HasOne("CarRental.API.Entities.Vehicle", "Vehicle")
                        .WithOne("RentalCondition")
                        .HasForeignKey("CarRental.API.Entities.RentalCondition", "CarId");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("CarRental.API.Entities.Vehicle", b =>
                {
                    b.Navigation("PricingPolicies");

                    b.Navigation("RentalCondition");
                });
#pragma warning restore 612, 618
        }
    }
}
